Decision tree improvements
jbteves/tedana pull request #4
Opened 2021-11-02 14:22 UTC by handwerkerd

Closes # .

Changes proposed in this pull request:

-
-

2021-11-09 01:16 UTC, jbteves requested changes
Noted mostly typos, but this is much better documented. Looking forward to discussing further.

2021-11-09 01:16 UTC, jbteves commented on docs/building_decision_trees.rst
> +  have "clear_classification_tags" set to true. There might be special cases where someone might want to violate these rules
```suggestion
  have "clear_classification_tags" set to true. There might be special cases where someone might want to violate these rules,
```

2021-11-09 01:16 UTC, jbteves commented on docs/building_decision_trees.rst
> +  but, depending what else happens in preceding code, other functions will expect both of these columns to exist.
```suggestion
  but depending what else happens in preceding code, other functions will expect both of these columns to exist.
```

2021-11-09 01:16 UTC, jbteves commented on docs/building_decision_trees.rst
> +- Every possible path through the tree should result in each component being classified as 'accepted' or 'rejected'
```suggestion
- Every possible path through the tree should result in each component being classified as 'accepted' or 'rejected' by the time the tree is completed.
```

2021-11-09 01:16 UTC, jbteves commented on docs/building_decision_trees.rst
> +- "refs" Publications that should be referenced, when this tree is used
```suggestion
- "refs" Publications that should be referenced when this tree is used
```

2021-11-09 01:16 UTC, jbteves commented on docs/building_decision_trees.rst
> +- "refs" Publications that should be referenced, when this tree is used
Should we also use this field to specify the equivalent of a "see also"?

2021-11-09 01:16 UTC, jbteves commented on docs/building_decision_trees.rst
> +The "nodes" field is a list of elements where each element defines a node the decision tree. There are several key fields for each of these nodes:
```suggestion
The "nodes" field is a list of elements where each element defines a node in the decision tree. There are several key fields for each of these nodes:
```

2021-11-09 01:16 UTC, jbteves commented on docs/building_decision_trees.rst
> +the components a function should be applied to. It can be a single classification, or a comma separated string of classificaions.
```suggestion
the components a function should be applied to. It can be a single classification, or a comma separated string of classifications.
```

2021-11-09 01:16 UTC, jbteves commented on docs/building_decision_trees.rst
> +Code the executes ``outputs["node_label"] = custom_node_label`` if there is a user-inputted custom node label or assigned a default node label. The default node lable
I'm not sure what is meant by "code the executes" here.

2021-11-09 01:16 UTC, jbteves commented on docs/building_decision_trees.rst
> +Then run ``confirm_metrics_exist`` which is an added check to make sure the metrics used by this function exist in the component table.
```suggestion
and then run ``confirm_metrics_exist`` which is an added check to make sure the metrics used by this function exist in the component table.
```

2021-11-09 01:16 UTC, jbteves commented on docs/building_decision_trees.rst
> +For decision functions the key variable is ``decision_boolean`` which should be a dataframe column which is True or False based on the function's criteria.
What should be expected for components which don't meet the criteria for being included in the decision. NaN? False? Blank?

2021-11-09 01:16 UTC, jbteves commented on docs/building_decision_trees.rst
> +This returns makes sure the outputs from the function are saved in the class structure and the class structure is return.
```suggestion
This returns makes sure the outputs from the function are saved in the class structure and the class structure is returned.
```

2021-11-09 01:16 UTC, jbteves commented on docs/building_decision_trees.rst
> +If you follow these simple steps you'll be able design your very own decision tree functions.
```suggestion
If you follow these steps you'll be able design your very own decision tree functions.
```

2021-11-09 01:16 UTC, jbteves commented on docs/building_decision_trees.rst
> +If you follow these simple steps you'll be able design your very own decision tree functions.
Per your previous guidance, we want to avoid describing things as "simple" so as not to alienate confused users.

2021-11-09 01:16 UTC, jbteves commented on tedana/metrics/collect.py
> +    #     }
Why is this commented? If it's not being used it should just be deleted.

2021-11-09 01:16 UTC, jbteves commented on tedana/selection/_utils.py
> +    selector
```suggestion
    selector.
```

2021-11-09 01:16 UTC, jbteves commented on tedana/selection/_utils.py
> +                if tmpstr != "":
I won't let this stop merging, but this code is repeated below, ideally we should find a way to make this some sort of function.

2021-11-09 01:16 UTC, jbteves commented on tedana/selection/_utils.py
> +    # comptable["rationale"] = comptable["rationale"].str.rstrip(";")
Why is this commented? If it's unused it should be deleted.

2021-11-09 02:35 UTC, handwerkerd commented on tedana/metrics/collect.py
> +    #     }
I wasn't 100% sure what this did, but I knew it was irrelevant when I removed rationale. I wanted to confirm that I shouldn't be replacing this with classification_tags in some form.

2021-11-09 03:26 UTC, handwerkerd commented on docs/building_decision_trees.rst
> +the components a function should be applied to. It can be a single classification, or a comma separated string of classificaions.
You have no clue how many typos of "classification" kept finding. If this is the only one I missed, I'd be impressed with myself.

2021-11-09 03:26 UTC, handwerkerd commented on docs/building_decision_trees.rst
> +If you follow these simple steps you'll be able design your very own decision tree functions.
That was tongue-in-cheek. I'm actually thinking about how to make this more extreme so that it's more obvious this is a joke.

2021-11-11 22:45 UTC, handwerkerd commented on docs/building_decision_trees.rst
> +rejected. The time series for the rejected components are regressed from the data in the final denoising step.
I'm going to change this to bolded text. Right now, classification labels are case sensitive and all lowercase and I don't want to add confusion by sometimes capitalizing.  Should case-insensitivity could be an enhancement?

2021-11-11 22:45 UTC, handwerkerd commented on docs/building_decision_trees.rst
> +A user can specify another decision tree and link to the tree location when tedana is executed. The format is
Will be viewable with the next push.

2021-11-11 22:45 UTC, handwerkerd commented on docs/building_decision_trees.rst
> +Code the executes ``outputs["node_label"] = custom_node_label`` if there is a user-inputted custom node label or assigned a default node label. The default node lable
Reworded after next push.

2021-11-11 22:45 UTC, handwerkerd commented on docs/building_decision_trees.rst
> +For decision functions the key variable is ``decision_boolean`` which should be a dataframe column which is True or False based on the function's criteria.
Only components with classifications in comps2use are included in decision_boolean. Excluded components retain their existing classifications. I added some text to make that more clear.

2021-11-11 22:45 UTC, handwerkerd commented on docs/building_decision_trees.rst
> +If you follow these simple steps you'll be able design your very own decision tree functions.
The revised version is a bit more tongue-in-cheek. Better?

2021-11-11 22:45 UTC, handwerkerd commented on tedana/metrics/collect.py
> +    #     }
I realized this section of the code needed metadata for classification_tags. That is now added and I edited the metadata for the rationale take to include "This column label was replaced with classification_tags in late 2021"

2021-11-12 15:28 UTC, jbteves commented on tedana/selection/_utils.py
> +                if tmpstr != "":
It's too large for a lambda, but no big deal.

2021-11-12 16:13 UTC, handwerkerd commented on tedana/selection/_utils.py
> +                if tmpstr != "":
Look at the current code. When I added additional code to log a warning if a component is changed away from accepted or rejected, I split this off into a stand-alone function so that there is no longer repetition.

2021-11-12 16:18 UTC, handwerkerd commented on docs/building_decision_trees.rst
> +rejected. The time series for the rejected components are regressed from the data in the final denoising step.
I added case-insensitivity to the TODO list for the main PR.

2021-11-12 18:35 UTC, handwerkerd commented on docs/building_decision_trees.rst
> +This might be useful both if one of the default decision trees needs to be slightly altered due to the nature
Not completely sure what you're referring to with this comment. Maybe I changed something already?

2021-11-12 19:42 UTC, jbteves commented on docs/building_decision_trees.rst
> +If you follow these simple steps you'll be able design your very own decision tree functions.
Much.

2021-11-12 19:45 UTC, merged