Full kundu decision tree that runs!
jbteves/tedana pull request #9
Opened 2022-08-03 00:45 UTC by handwerkerd

This has all steps in the kundu decision tree and it runs. I should still look it over a few more times and directly compare it to the decision tree in the current code (and maybe back to the meica 2.7 code for a few things that seem slightly odd). 

There should be full testing coverage of everything new and all tests pass except for `test_integration_four_echo`. I get the error:
`./tedana/tests/test_integration.py::test_integration_four_echo Failed: [undefined]FileNotFoundError: [Errno 2] No such file or directory: '/tmp/data/four-echo/TED.four-echo/desc-tedana_registry.json'` I'm not sure why 4 echo uses the registry and the other integration tests don't, but I suspect you can figure that out better than I can.

There's only one bit of functionality I had to drop and I'm not losing sleep over it. I have a node that calculates the X percentile variance over a subset of components. There's another variable that's an estimate of the number of accepted components. For one of the 3 times the percentile of the variance is calculated, it's not only done on a subset of components, but only on components 0:num_acc_guess sorted by lowest to highest variance. I can add this to the code, but I don't think it will make a huge difference, & this is close enough for now.

2022-08-04 18:14 UTC, jbteves requested changes
Very small typos and a few more notes, otherwise looks good.

2022-08-04 18:14 UTC, jbteves commented on tedana/selection/selection_nodes.py
> +    """
Could we add a small note about a context in which this is useful?

2022-08-04 18:14 UTC, jbteves commented on tedana/selection/selection_nodes.py
> +    note will suffice for now.
```suggestion
    note will hopefully suffice for now.
```

2022-08-04 18:14 UTC, jbteves commented on tedana/selection/selection_utils.py
> +       If so, then figure out why an fix or remove spaces: x = [s.replace(‘ ‘, ‘’) for s in x]
I believe we should remove this, as that doesn't seem to be the issue, unless I'm mixing problems.

2022-08-04 18:14 UTC, jbteves commented on tedana/selection/selection_utils.py
> +        none, but that's not an problem. Set comps_needed to False so that a warning is
This wording confused me a bit. Isn't comps2use a problem, rather than not a problem? I'm wrong, then it should still be "that's not a problem".

2022-08-05 20:30 UTC, handwerkerd commented on tedana/selection/selection_utils.py
> +        none, but that's not an problem. Set comps_needed to False so that a warning is
I realized `comps_needed` was only used in a single function. I ended up creating a new option for `comps2use==-1` which would do the same thing. Read the new docstring in this function to see if it makes more sense.

2022-08-05 20:30 UTC, handwerkerd commented
I think I addressed these comments and I also went through `building_decision_trees.rst` to improve text and make sure it still matches the code.

2022-08-08 19:51 UTC, jbteves commented on docs/building_decision_trees.rst
> +    execution. Of particularly note, each output includes a list of the metrics
```suggestion
    execution. Of particular note, each output includes a list of the metrics
```

2022-08-08 19:53 UTC, jbteves commented on docs/building_decision_trees.rst
> +    since it was done as part of the original decision tree processed defined in meica
```suggestion
    since it was done as part of the original decision tree process defined in meica
```

2022-08-08 20:03 UTC, merged